# 1. Introduction

Why do we need Generators? There are mainly two reasons:

    - Firstly, the codes look nicer
    - Secondly and more importantly, the performance is much better than simply using the iterator, espeically when you have a lot if items
    
This jupter 

In [50]:
import numpy as np
import time

In [42]:
def square_numbers(nums):
    result = []
    for i in nums:
        result.append(i**2)
    return result

In [43]:
my_nums = square_numbers([2,3,4,5])
my_nums

[4, 9, 16, 25]

However, we could also use the **yield** to create a generator like the following:

In [44]:
def square_numbers(nums):
    for i in nums:
        yield i**2

In [45]:
my_nums = square_numbers([2,3,4,5])
# print(next(my_nums))
# print(next(my_nums))
# print(next(my_nums))
# print(next(my_nums))

In [46]:
for num in my_nums:
    print(num)

4
9
16
25


The code is much simpler than the previous function

# 2. Different ways of creating a generator

In [47]:
my_nums = [x*x for x in [1,2,3,4,5]]

print(my_nums)

for num in my_nums:
    print(num)

[1, 4, 9, 16, 25]
1
4
9
16
25


However, we could also construct a generator like the following:

We could notice that when implementing the function:

```Python
print(my_nums)
```
a generator object is created!

In [48]:
my_nums = (x*x for x in [1,2,3,4,5])

print(my_nums)

for num in my_nums:
    print(num)
    
# Once you have use the print(num) statement here, the following my_nums_list would be []

<generator object <genexpr> at 0x000001DE1A236A40>
1
4
9
16
25


We could convert the generator object to a list by simply calling a list function:

In [49]:
my_nums = (x*x for x in [1,2,3,4,5])

my_nums_list = list(my_nums)
my_nums_list

[1, 4, 9, 16, 25]

Fianlly we give an example about how generator improves performance

In [54]:
a = np.random.rand(1000000, 1)

In [59]:
def square_numbers(nums):
    result = []
    for i in nums:
        result.append(i**2)
    return result

In [60]:
time1 = time.clock()
result_nums = square_numbers(a)
time2 = time.clock()
print('Total time cost: ', time2-time1)

Total time cost:  1.3185868611245155


In [64]:
result_nums

[array([0.18142827]),
 array([0.09653164]),
 array([0.32273337]),
 array([0.36241892]),
 array([0.01293177]),
 array([0.13066097]),
 array([0.0518875]),
 array([0.30394557]),
 array([0.66149774]),
 array([0.01788371]),
 array([0.35308992]),
 array([0.00325107]),
 array([0.00104364]),
 array([0.14690931]),
 array([0.4581079]),
 array([7.12473875e-06]),
 array([0.16137738]),
 array([0.16823029]),
 array([0.10793038]),
 array([0.15326702]),
 array([0.3185399]),
 array([0.35441051]),
 array([0.40621567]),
 array([0.09662235]),
 array([0.19859532]),
 array([0.02059418]),
 array([0.00786044]),
 array([0.12508128]),
 array([0.33196269]),
 array([0.31195284]),
 array([0.11972702]),
 array([0.33060366]),
 array([0.60658883]),
 array([0.45786105]),
 array([0.62090862]),
 array([0.14009548]),
 array([6.50419628e-05]),
 array([0.01405655]),
 array([0.03716944]),
 array([0.00152242]),
 array([0.69048947]),
 array([0.73578714]),
 array([0.24267621]),
 array([0.6059607]),
 array([0.77270799]),
 array

Howoever, if we use the generator:

In [65]:
def square_numbers(nums):
    for i in nums:
        yield i**2

In [71]:
time3 = time.clock()
result_nums_generator = square_numbers(a)
time4 = time.clock()
print('Total time cost: ', time4-time3)

Total time cost:  5.845340814403244e-05


In [72]:
result_nums_generator

<generator object square_numbers at 0x000001DE2933ADB0>

In [73]:
print(next(result_nums_generator))
print(next(result_nums_generator))

[0.18142827]
[0.09653164]
